# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170422_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='id_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.Point'),
        ),
    ]
