# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170527_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='badge',
            name='name',
            field=models.CharField(default='tets\x08\x08st\x08\x08t', max_length=50),
            preserve_default=False,
        ),
    ]
