# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170527_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('badge_acquiring_date', models.DateTimeField()),
                ('activation_modification_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(default='', help_text='More thorough information about badge acquiring (i.e. criteria)', max_length=256),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(help_text='describes in short name of the badge', max_length=50),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='id_badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Badge'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='id_route',
            field=models.ForeignKey(help_text='id of route on which badge has been acquired', on_delete=django.db.models.deletion.CASCADE, to='web.Route'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User'),
        ),
    ]
