# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170528_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='time',
            field=models.DateTimeField(default='2017-03-03T12:00:00+00:00'),
        ),
    ]
